version: "3.11"
services:
  db:
    image: postgres:16
    container_name: db_video-hosting
    command: -p 5432
    restart: always
    environment:
      POSTGRES_PASSWORD: true
    expose:
      - 5432
    env_file:
      - .env-non-dev

  redis:
    image: redis:7
    container_name: redis_video-hosting
    command: --port 6379
    expose:
      - 6379

  app:
    build: .
    env_file:
      - .env-non-dev
    container_name: app_video-hosting
    command: ["/video-hosting_app/docker/app.sh"]
    ports:
      - "9999:8000"
    depends_on:
      - db
      - redis

#  celery:
#    build:
#      context: .
#    container_name: celery_app
#    command: ["/video-hosting_app/docker/celery.sh", "celery"]
#    depends_on:
#      - redis
